[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
android_logger = "0.13"
log = "0.4"
anyhow = "1"
flutter_rust_bridge = "1"
